---
title: 'Data Wrangling Exercise 2: Dealing with missing values'
author: "Shyamala Gurumurthy"
date: "December 29, 2017"
output: 
  html_document: 
    df_print: paged
---

## Exercise
Using R, handle the missing values in the titanic data set, and create a new data set.

```{r setup, include=FALSE}
library(knitr)
library(magrittr)
library(tidyverse)
knitr::opts_chunk$set(cache=TRUE, message=FALSE)
```

#### 0: Load the data in RStudio
```{r}
titanic <- read.csv('C:/Users/User/Desktop/R_Practice/Exercise_2_Titanic/titanic_original.csv', header = TRUE)
```


#### 1: Port of embarkation
```{r}
sum(grepl("^\\s*$",titanic$embarked))

titanic <- titanic %>%
  mutate(embarked = gsub("^\\s*$","S", embarked)) 

sum(grepl("^\\s*$",titanic$embarked))
```


#### 2: Age
```{r}
sum(is.na(titanic$age))

mean_age <- mean(titanic$age, na.rm=TRUE) 
titanic <- titanic %>%
  mutate(age = if_else(is.na(age), mean_age, age))

sum(is.na(titanic$age))
```


#### 3: Lifeboat
```{r}
sum(grepl("^\\s*$",titanic$boat))

titanic <- titanic %>%
  mutate(boat = gsub("^\\s*$","None", boat))

sum(grepl("^\\s*$",titanic$boat))
```


#### 4: Cabin
```{r}
titanic <- titanic %>%
  mutate(has_cabin_number = ifelse(grepl("^\\s*$",cabin), 0, 1))

titanic
```

```{r}
write.csv(titanic, file='C:/Users/User/Desktop/R_Practice/Exercise_2_Titanic/titanic_clean.csv')
```

